const Data = [
    {
        id: '1',
        author: 'Olawoyin',
        name: 'HAVIT HV-G92 Gamepad',
        category: "Today's",
        image: '../images/new.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "200",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '2',
        author: 'Olawoyin',
        name: 'AK-900 Wired Keyboard',
        category: "Today's",
        image: '../images/item1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "120",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '3',
        author: 'Olawoyin',
        name: "IPS LCD Gaming Monitor",
        category: "Today's",
        image: '../images/item3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "220",
        discount: "40",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '4',
        author: 'Olawoyin',
        name: "S-Series Comfort Chair",
        image: '../images/prod8.png',
        category: "Today's",
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "130",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '5',
        author: 'Olawoyin',
        name: "hello",
        category: "Today's",
        image: '../images/item9.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "110",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "",
        image: '../images/blog6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "300",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "",
        image: '../images/blog6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "300",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '8',
        author: 'Gbolahan',
        name: "Pendleton vintage",
        category: "Men's Clothing",
        image: '../images/f1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "230",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '9',
        author: 'Gbolahan',
        name: "Ralph Lauren vintage",
        category: "Men's Clothing",
        image: '../images/f2.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "220",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '10',
        author: 'Gbolahan',
        name: "Brooks Brothers vintage",
        category: "Men's Clothing",
        image: '../images/f3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "110",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '11',
        author: 'Gbolahan',
        name: "L.L. Bean",
        category: "Men's Clothing",
        image: '../images/f4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "100",
        discount: "40",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '12',
        author: 'Gbolahan',
        name: "Tommy Hilfiger",
        category: "Men's Clothing",
        image: '../images/f5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "90",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '13',
        author: 'Gbolahan',
        name: "Ralph Lauren",
        category: "Men's Clothing",
        image: '../images/f6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "Wrangler",
        category: "Men's Clothing",
        image: '../images/n6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "99",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '16',
        author: 'Gbolahan',
        name: "Gant vintage T-shirt",
        category: "Men's Clothing",
        image: '../images/n4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "78",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '17',
        author: 'Gbolahan',
        name: "Munsingwear",
        category: "Men's Clothing",
        image: '../images/n1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "100",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '18',
        author: 'Gbolahan',
        name: "Kennington shirt",
        category: "Men",
        image: '../images/n2.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "100",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '19',
        author: 'Gbolahan',
        name: "hello",
        category: "",
        image: '../images/n3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "90",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '20',
        author: 'Gbolahan',
        name: "Farah",
        category: "Women's Clothing",
        image: '../images/w1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "80",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '21',
        author: 'Gbolahan',
        name: "Sears Roebuck",
        category: "Women's Clothing",
        image: '../images/w2.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "99",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '22',
        author: 'Gbolahan',
        name: "Stetson",
        category: "Women's Clothing",
        image: '../images/w3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "110",
        discount: "10",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '23',
        author: 'Gbolahan',
        name: "Hathaway",
        category: "Women's Clothing",
        image: '../images/n8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "110",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '24',
        author: 'Gbolahan',
        name: "Jantzen",
        category: "Women's Clothing",
        image: '../images/n7.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "100",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '27',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/n5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "120",
        discount: "",
        newPrice: "",
        totalRating: "42",
        title: "",
    },
    {
        id: '28',
        author: 'Gbolahan',
        name: "Arrow vintage",
        category: "Women's Clothing",
        image: '../images/n4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "110",
        discount: "10",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '29',
        author: 'Gbolahan',
        name: "Sears Roebuck",
        category: "Women's Clothing",
        image: '../images/n1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "140",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '30',
        author: 'Olawoyin',
        name: "Small BookSelf",
        category: "Trending",
        image: '../images/item6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "200",
        discount: "10",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '31',
        author: 'Olawoyin',
        name: "Shirt Series 1",
        category: "Trending",
        image: '../images/f6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "99",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '32',
        author: 'Gbolahan',
        name: "Jr. Zoom Soccer Cleats",
        category: "Trending",
        image: '../images/item10.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "360",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '33',
        author: 'Gbolahan',
        name: "The north coat",
        category: "Trending",
        image: '../images/prod4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "260",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '34',
        author: 'Gbolahan',
        name: "JBL Beatbox v2",
        category: "Trending",
        image: '../images/item8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "210",
        discount: "40",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '37',
        author: 'Gbolahan',
        name: "GP11 Shooter USB Gamepad",
        category: "Trending",
        image: '../images/item9.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "310",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '38',
        author: 'Gbolahan',
        name: "RGB liquid CPU Cooler",
        category: "Trending",
        image: '../images/item5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "89",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '39',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "90",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '40',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "100",
        discount: "10",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '41',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "200",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '42',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "92",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '43',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/prod8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "99",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '44',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/prod7.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "100",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '47',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "130",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
   
]

export default Data