const Data = [
    {
        id: '1',
        author: 'Olawoyin',
        name: 'HAVIT HV-G92 Gamepad',
        category: "Today's",
        image: '../images/new.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '2',
        author: 'Olawoyin',
        name: 'AK-900 Wired Keyboard',
        category: "Today's",
        image: '../images/item1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "20",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '3',
        author: 'Olawoyin',
        name: "IPS LCD Gaming Monitor",
        category: "Today's",
        image: '../images/item3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "40",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '4',
        author: 'Olawoyin',
        name: "S-Series Comfort Chair",
        image: '../images/prod8.png',
        category: "Today's",
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '5',
        author: 'Olawoyin',
        name: "hello",
        category: "Today's",
        image: '../images/item9.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "",
        image: '../images/blog6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "",
        image: '../images/blog6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/f1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/f2.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/f3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/f4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/f5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/f6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/n6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/n4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men's Clothing",
        image: '../images/n1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "Men",
        image: '../images/n2.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '6',
        author: 'Gbolahan',
        name: "hello",
        category: "",
        image: '../images/n3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/w1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/w2.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/w3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/n8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/n7.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/n5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/n4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '7',
        author: 'Gbolahan',
        name: "hello",
        category: "Women's Clothing",
        image: '../images/n1.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
    },
    {
        id: '8',
        author: 'Olawoyin',
        name: "Small BookSelf",
        category: "Technology",
        image: '../images/blog8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '9',
        author: 'Olawoyin',
        name: "RGB liquid CPU Cooler",
        category: "Trending",
        image: '../images/f6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '10',
        author: 'Gbolahan',
        name: "Gucci duffle bag",
        category: "Trending",
        image: '../images/item10.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "360",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '11',
        author: 'Gbolahan',
        name: "The north coat",
        category: "Trending",
        image: '../images/image5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "260",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '12',
        author: 'Gbolahan',
        name: "hello",
        category: "Trending",
        image: '../images/item8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '13',
        author: 'Gbolahan',
        name: "hello",
        category: "Trending",
        image: '../images/item4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Trending",
        image: '../images/item5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item3.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item5.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item6.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/prod8.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/prod7.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
    {
        id: '14',
        author: 'Gbolahan',
        name: "hello",
        category: "Home & Lifestyle",
        image: '../images/item4.png',
        description: 'PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.',
        price: "",
        discount: "",
        newPrice: "",
        totalRating: "40",
        title: "",
        
    },
   
]

export default Data